[build-system]
build-backend = "backend"
requires = [
  "setuptools>=67.8",
]
backend-path = [
  "_custom_build",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "-ra --color=yes"
testpaths = ["Tests"]
